sudo: false
language: node_js
node_js: 8
install:
  - npm install
cache:
  directories:
  - node_modules
notifications:
  email:
    - web@oakenfold.ca
branches:
  only:
  - master
before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  ##- npx cypress verify &
  - npm install -D webpack-cli
  - npx webpack -p --config /home/travis/build/coakenfold/bookstore/webpack.config.js --display-error-details --progress
script:
  - npm run test
## after_success:
## - npx codecov
