sudo: false
language: node_js
node_js: 8
install: true
cache:
  directories:
  - node_modules
notifications:
  email:
    - web@oakenfold.ca
branches:
  only:
  - master
before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - npx cypress verify &
script:
  - npm run test:run
## after_success:
## - npx codecov
